server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: wokee
  http:
    encoding:
      enabled: true
      charset: utf-8
      force: true

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 1
        max-wait: -1

  freemarker:
    check-template-location: false